# -*- coding: utf-8 -*-
{
    'name': 'TG HR',
    'version': '19.0.1.0.0',
    'category': 'Human Resources',
    'summary': 'HR extensions',
    'author': 'Tiger-Zebin',
    'depends': [
        'base_by_zb',
        'base_user_role',
        'hr',
        'hr_skills',
        'hr_payroll',
        'hr_recruitment',
        'hr_contract_salary',
        'documents',
        'mail',
        'sign',
        'base_tier_validation',
        'base_tier_validation_server_action',
        'base_tier_validation_extend_by_zb'
    ],
    'data': [
        'security/tg_hr_groups.xml',
        'security/ir.model.access.csv',
        'data/hr_requisition_stage_data.xml',
        'data/hr_applicant_stage_data.xml',
        # ir.rule 中 ref 本模块 Offered 阶段，须在 hr_applicant_stage_data 之后加载
        'security/tg_hr_record_rules.xml',
        'data/cron_offer_t3_warning.xml',
        'data/resource_calendar_bd_data.xml',
        'data/mail_template_offer_data.xml',
        'views/hr_requisition_stage_views.xml',
        'views/hr_requisition_views.xml',
        'views/hr_job_views.xml',
        'wizards/hr_applicant_review_wizard_views.xml',
        'wizards/hr_applicant_first_contact_wizard_views.xml',
        'wizards/hr_applicant_interview_wizard_views.xml',
        'wizards/hr_applicant_create_employee_wizard_views.xml',
        'wizards/hr_offer_mark_signed_offline_wizard_views.xml',
        'wizards/hr_employee_confirm_contract_wizard_views.xml',
        'views/hr_applicant_views.xml',
        'views/hr_applicant_generate_offer_tg.xml',
        'views/hr_version_search_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_employee_public_views.xml',
        'views/hr_version_views.xml',
        'views/hr_payroll_structure_type_views.xml',
        # Tier Validation 配置数据（审批流/动作）
        'data/tier_validation_data.xml',
        'views/res_users_views.xml',
        'views/mail_template_views.xml',
        'views/menuitems.xml',
        'report/tg_hr_applicant_report_views.xml',
        'data/tg_hr_user_roles.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'tg_hr/static/src/js/hr_applicant_form_page_focus.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
